export const TYPES = {
  AzureAPI: "AzureAPI",
  IPersonaRepository: "IPersonaRepository",
  IDepartamentoRepository: "IDepartamentoRepository",
  IObtenerPersonasUseCase: "IObtenerPersonasUseCase",
  ICrearPersonaUseCase: "ICrearPersonaUseCase",
  IActualizarPersonaUseCase: "IActualizarPersonaUseCase",
  IEliminarPersonaUseCase: "IEliminarPersonaUseCase",
  IObtenerDepartamentosUseCase: "IObtenerDepartamentosUseCase",
  ICrearDepartamentoUseCase: "ICrearDepartamentoUseCase",
  IActualizarDepartamentoUseCase: "IActualizarDepartamentoUseCase",
  IEliminarDepartamentoUseCase: "IEliminarDepartamentoUseCase",
  PersonasVM: "PersonasVM",
  DepartamentosVM: "DepartamentosVM",
} as const;